---
# bootstrap-ceph-dashboard

ceph_dashboard_username: admin

# keycloak

kcadm_binary: "/opt/jboss/keycloak/bin/kcadm.sh"
keycloak_realm: "osism"
keycloak_url: "http://localhost:8080/keycloak"
keycloak_service_container_name: "keycloak"

# keycloak-ldap-federation-config

keycloak_ldap_storage_provider_component_name: "ldap-provider"
keycloak_ldap_user: "keycloak-user"
keycloak_ldap_binddn: "uid={{ keycloak_ldap_user }},{{ ldap_users }}"

# keycloak-oidc-client-config

keycloak_admin_id: "admin"
keycloak_key_provider_component_name: "rsa-for-keystone"

keystone_client_id: "keystone"
keystone_redirect_uris:
  - "http://api.testbed.osism.xyz:5000/redirect_uri"
  - "http://api.testbed.osism.xyz"
  - "http://192.168.16.254:5000/redirect_uri"
  - "http://192.168.16.254"

private_key_file_path: "{{ configuration_directory }}/environments/custom/files/keycloak/private_key.pem"
private_key_data: "{{ lookup('file', private_key_file_path)| regex_replace('\n', '\\\\n') }}"

certificate_file_path: "{{ configuration_directory }}/environments/custom/files/keycloak/cert.crt"
certificate_data: "{{ lookup('file', certificate_file_path)| regex_replace('\n', '\\\\n') }}"

# openldap
openldap_service_container_name: "openldap"
ldap_base: "dc=osism,dc=local"
# In case of OpenLDAP this should be {{ openldap_password }}
ldap_password: password
ldap_url: "ldap://{{ openldap_host }}:389"
ldap_users: "cn=users,{{ ldap_base }}"

# umc-config
umc_ldap_user: "umc-admin"
umc_ldap_binddn: "uid={{ umc_ldap_user }},{{ ldap_users }}"
