---
- name: Pull images
  hosts: manager

  vars:
    images:
      - common
      - glance
      - ironic
      - loadbalancer
      - mariadb
      - memcached
      - rabbitmq
      - redis

  tasks:
    - name: Pull keystone image
      ansible.builtin.command:
        cmd: "osism apply -a pull keystone -l {{ groups['control'] | first }}"
      environment:
        INTERACTIVE: "false"
      changed_when: true

    - name: Pull other images
      ansible.builtin.command:
        cmd: "osism apply --no-wait -a pull {{ item }} -l {{ groups['control'] | first }}"
      environment:
        INTERACTIVE: "false"
      loop: "{{ images }}"
      changed_when: true
