---
- name: Preload stable ceph & openstack images
  hosts: testbed-nodes
  gather_facts: false

  vars:
    images_ceph:
      - ceph-daemon:17.2.6

    images_openstack:
      - keystone:22.0.1.20230902  # 5.3.0
      - keystone:23.0.1.20230919  # 6.0.2

  tasks:
    - name: Import stable ceph images
      ansible.builtin.command:
        cmd: "skopeo copy dir:/home/dragon/images/{{ item }} docker-daemon:osism.harbor.regio.digital/osism/{{ item }}"
      loop: "{{ images_ceph }}"

    - name: Import stable openstack images
      ansible.builtin.command:
        cmd: "skopeo copy dir:/home/dragon/images/{{ item }} docker-daemon:osism.harbor.regio.digital/kolla/release/{{ item }}"
      loop: "{{ images_openstack }}"
