---
- name: Manage cronjobs on the manager node
  hosts: manager
  gather_facts: false

  tasks:
    - name: Run helper scripts non-interactive
      cron:
        name: INTERACTIVE
        env: true
        value: "false"
        cron_file: osism
        user: "{{ operator_user }}"
      become: true

    - name: Gather facts
      cron:
        name: "gather facts"
        minute: "15"
        hour: "*/6"
        job: /usr/local/bin/osism-run-without-secrets generic facts
        cron_file: osism
        user: "{{ operator_user }}"
      become: true
