---
- name: Prepare storage nodes for cinder dm-clone driver
  hosts: storage
  gather_facts: true

  tasks:
    - name: Create physical volumes and volume group on empty disks
      become: true
      community.general.lvg:
        vg: local
        pvresize: true
        pvs: >-
          {{
            ['/dev']
            | product(
                ansible_facts['ansible_local']['testbed_ceph_osd_devices_all']
                | dict2items
                | map(attribute='key')
                | list
                | difference(
                    ansible_facts['ansible_local']['testbed_ceph_osd_devices']
                    | dict2items
                    | map(attribute='key')
                    | list
                )
            )
            | map('join', '/')
            | list
          }}
    - name: Checkout cinder dm-clone driver
      become: true
      ansible.builtin.git:
        repo: https://github.com/osism/cinder-driver-dm-clone.git
        dest: "/opt/cinder-driver-dm-clone"
        update: true
        version: main
