---
- name: Pull images
  hosts: manager

  vars:
    images:
      - barbican
      - cinder
      - common
      - designate
      - glance
      - grafana
      - heat
      - horizon
      - keystone
      - loadbalancer
      - mariadb
      - memcached
      - neutron
      - nova
      - octavia
      - opensearch
      - openvswitch
      - ovn
      - placement
      - rabbitmq
      - redis

  tasks:
    - name: Pull images
      ansible.builtin.command:
        cmd: "osism apply -a pull {{ item }}"
      environment:
        INTERACTIVE: "false"
      loop: "{{ images }}"
      changed_when: true
      async: 3600
      poll: 0
      register: async_results

    - name: Check sync status
      ansible.builtin.async_status:
        jid: "{{ async_result_item.ansible_job_id }}"
      loop: "{{ async_results.results }}"
      loop_control:
        loop_var: "async_result_item"
      register: async_poll_results
      until: async_poll_results.finished
      delay: 10
      retries: 360
