---
- name: Prepare baremetal deployment
  hosts: testbed-managers

  tasks:
    - name: Add resource nodes to tenks hypervisors
      ansible.builtin.copy:
        content: |
          [libvirt:children]
          testbed-resource-nodes
        dest: /opt/configuration/inventory/50-tenks.yml
        mode: '0644'
        owner: dragon
        group: dragon

    - name: Add networks to testbed-node group_vars
      ansible.builtin.copy:
        content: |
          {% raw -%}
          ---
          _network_vxlan_interface_vxlan_oob:
            vxlan-oob:
              vni: 65
              mtu: 1350
              local_ip: "{{ [inventory_hostname] | map('extract', hostvars, 'ansible_facts') | map(attribute=internal_interface) | map(attribute='ipv4') | map(attribute='address') | first }}"
              dests: "{{ groups['testbed-nodes'] | reject('equalto', inventory_hostname) | map('extract', hostvars, 'ansible_facts') | map(attribute=internal_interface) | map(attribute='ipv4') | map(attribute='address') | list }}"
              addresses:
                - "{{ '172.16.0.0/20' | ansible.utils.ipaddr('net') | ansible.utils.ipaddr(node_id) | ansible.utils.ipaddr('address') }}/20"
          network_vxlan_interfaces: "{{ _network_vxlan_interfaces | combine(_network_vxlan_interface_vxlan_oob) }}"
          {% endraw -%}
        dest: "{{ item }}"
        mode: '0644'
        owner: dragon
        group: dragon
      loop:
        - /opt/configuration/inventory/group_vars/testbed-control-nodes.yml
        - /opt/configuration/inventory/group_vars/testbed-resource-nodes.yml
