---
##########################
# k3s

cilium_bgp: true
cilium_bgp_lb_cidr: "172.31.252.0/23"
cilium_hubble: true

##########################
# rook

rook_network_public: 192.168.128.0/20

rook_cephconfig:
  client.rgw.rgw.a:
    rgw_keystone_verify_ssl: "false"
    rgw_verify_ssl: "false"

rook_storage_devicefilter: "^sd[b-c]"
rook_storage_nodes:
  - name: testbed-node-3
  - name: testbed-node-4
  - name: testbed-node-5

# reduce resources to fit into testbed
rook_resources_cephfilesystem:
  limits:
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "4Gi"
rook_resources_cephobjecstore:
  limits:
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

rook_dashboard:
  enabled: true
  port: 7000
  ssl: false

# set to true to enable monitoring
# rook_monitoring_enabled: true

# set to true to enable cleanup
# rook_cleanup: true
## keystone
rook_cephobjectstore_keystone_acceptedRoles:
  - admin
  - member
rook_cephobjectstore_keystone_implicitTenants: "true"
rook_cephobjectstore_keystone_url: "https://api-int.testbed.osism.xyz:5000"
rook_cephobjectstore_swift_urlPrefix: "swift"
## keystone user
rook_cephobjectstore_keystone_auth_type: "password"
rook_cephobjectstore_keystone_project_domain_name: "Default"
rook_cephobjectstore_keystone_project_name: "service"
rook_cephobjectstore_keystone_user_domain_name: "Default"
rook_cephobjectstore_keystone_username: "ceph_rgw"
