---
extends: default

rules:
  comments: enable
  line-length: disable

ignore: |
  .git
  .tox
  contrib/rally/tests/
  environments/infrastructure/secrets.yml
  environments/kolla/files/overlays/ceilometer/event_definitions.yaml
  environments/kolla/files/overlays/ceilometer/event_pipeline.yaml
  environments/kolla/files/overlays/ceilometer/pipeline.yaml
