---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - Ft2GWr5BtY9XZ8Kr66GsyB1/PvBiT3COz9NnLFqg0Rp/zRInou7FXx4qNaK48p88EyZQ8
          c3QV49MNgzNYy11ZK2NjWkSQd6kWZ3x2Bvhu/vYfYjRCLWH34LL+36lDbITcpYt7tiQFH
          IaaBfXc/lwBBEZMlpAhEDfcDXLRoSSdtcyP8SX8BtSCH4tlh/KYVkqJ/a2nNMtJF7l2Wj
          PF7qe17WI6NsYCb6QD33bfEX+qe9JOmkwAKxHFd6ucTZJe1D6JiYvXAlJR+FhGDOOurKX
          DRX6H48WB2L0qp/UQgY9mwR2eWqbfdAJg1AGJ3M+Y0j/Xi0do07h7cX2RCG6MC0HHRSIG
          wXSvIYN8m50AT0c3ofnMQ1Vtf7V60cctV4em5sLxyWacz/lHzHPzstjmnFB5BVOh5vbh6
          ygRlLMTUQTQzUlAJHhDlYc+ea2njSbq79RzQSto1buN0lNRQNp3VGTnbZyhp/B671NlVZ
          cC5o6qs8j7LyLKOo9lNnYi8CQw2KjRzv2rBMuUaRqIaGXu4U/R8sswy3j6YhA7BT4vUxv
          zUyw/6Ql1IhZo3X0jEE3WtfeUQvsWB0AXDX+xf2WoEVL5dObYP8X5RVsJj5qQ7Y8BK2qa
          HflOaQYaKWZSf+5kfBUByzQghil4tH4QQQUHszDs0Qtzop7yTp0AB1cqefAyY8=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

# Regiocloud
- nodeset:
    name: testbed-orchestrator
    nodes:
      - name: orchestrator
        label: testbed-orchestrator

# PCO
- nodeset:
    name: testbed-orchestrator-pco
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-pco

# Wavestack
- nodeset:
    name: testbed-orchestrator-wavestack
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-wavecon

- job:
    name: abstract-testbed-deploy
    abstract: true
    parent: base-extra-logs
    pre-run: playbooks/pre.yml
    nodeset: testbed-orchestrator
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    cleanup-run: playbooks/cleanup.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
      - osism/terraform-base
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^\.github/.*$
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explicitly bumped in the tenant configuration
    timeout: 16200
    vars:
      terraform_blueprint: testbed-default

- job:
    name: testbed-deploy-managerless
    parent: base-extra-logs
    nodeset: ubuntu-jammy-large
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    cleanup-run: playbooks/managerless/cleanup.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      cloud_env: managerless
      terraform_blueprint: testbed-managerless
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- job:
    name: testbed-deploy
    parent: abstract-testbed-deploy
    vars:
      tempest: true

- job:
    name: testbed-deploy-in-a-nutshell
    parent: abstract-testbed-deploy
    vars:
      nutshell: true

- job:
    name: testbed-upgrade
    parent: abstract-testbed-deploy
    run: playbooks/upgrade.yml
    timeout: 25200

- job:
    name: testbed-deploy-stable
    parent: abstract-testbed-deploy
    vars:
      manager_version: 7.1.1
      tempst: true

- job:
    name: testbed-upgrade-stable
    parent: abstract-testbed-deploy
    run: playbooks/upgrade-stable.yml
    vars:
      manager_version: 6.0.2
      manager_version_next: 7.1.1
    nodeset: testbed-orchestrator
    timeout: 25200

- job:
    name: testbed-deploy-pco
    parent: abstract-testbed-deploy
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-deploy-wavestack
    parent: abstract-testbed-deploy
    nodeset: testbed-orchestrator-wavestack

- job:
    name: testbed-upgrade-pco
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-upgrade-wavestack
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-wavestack

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - flake8
        - python-black
        - yamllint
    label:
      jobs:
        - testbed-deploy
        - testbed-deploy-stable
        - testbed-upgrade
        - testbed-upgrade-stable
    gate:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
        - python-black
        - testbed-deploy:
            branches: main
        - testbed-deploy-stable:
            branches: main
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-daily:
      jobs:
        - testbed-deploy-in-a-nutshell
        - testbed-deploy-managerless
        - testbed-deploy-stable
        - testbed-upgrade-stable
        # - testbed-deploy-pco
        # - testbed-deploy-wavestack
        # - testbed-upgrade-pco
        # - testbed-upgrade-wavestack
        - ansible-lint
        - flake8
        - python-black
        - yamllint
