---
- job:
    name: testbed-deploy
    parent: base-extra-logs
    nodeset:
      nodes:
        - name: orchestrator
          label: static-testbed
    run: playbooks/run.yaml
    post-run: playbooks/post.yaml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^doc/.*$
    timeout: 10800

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy
    gate:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy:
            branches: main
    post:
      jobs:
        - osism-publish-tox-docs-production:
            branches: main
    periodic-daily:
      jobs:
        - testbed-deploy
