---
- job:
    name: testbed-upgrade
    parent: base-extra-logs
    nodeset:
      nodes:
        - name: orchestrator
          label: testbed-orchestrator
    run: playbooks/upgrade.yml
    post-run: playbooks/post.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^doc/.*$
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 14400

- job:
    name: testbed-deploy
    parent: base-extra-logs
    nodeset:
      nodes:
        - name: orchestrator
          label: testbed-orchestrator
    pre-run: playbooks/pre.yml
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^doc/.*$
    timeout: 10800

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy
        - testbed-upgrade
    gate:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy:
            branches: main
    post:
      jobs:
        - osism-publish-tox-docs-production:
            branches: main
    periodic-daily:
      jobs:
        - testbed-deploy
        - testbed-upgrade
