---
- nodeset:
    name: testbed-orchestrator
    nodes:
      - name: orchestrator
        label: testbed-orchestrator

- nodeset:
    name: testbed-orchestrator-cleura
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-cleura

- nodeset:
    name: testbed-orchestrator-pco
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-pco

- nodeset:
    name: testbed-orchestrator-wavestack
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-wavecon

- job:
    name: testbed-deploy
    parent: base-extra-logs
    pre-run: playbooks/pre.yml
    nodeset: testbed-orchestrator
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^doc/.*$
    timeout: 10800

- job:
    name: testbed-upgrade
    parent: testbed-deploy
    run: playbooks/upgrade.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    nodeset: testbed-orchestrator-wavestack
    vars:
      testbed_environment: wavestack

- job:
    name: testbed-deploy-stable
    parent: testbed-deploy
    vars:
      testbed_environment: pluscloudopen
      manager_version: "4.2.0"
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-deploy-cleura
    parent: testbed-deploy
    vars:
      testbed_environment: cleura
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-deploy-pco
    parent: testbed-deploy
    vars:
      testbed_environment: pluscloudopen
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-deploy-wavestack
    parent: testbed-deploy
    vars:
      testbed_environment: wavestack
    nodeset: testbed-orchestrator-wavestack

- job:
    name: testbed-deploy-wavestack-zed
    parent: testbed-deploy
    vars:
      testbed_environment: wavestack
      openstack_version: zed
    nodeset: testbed-orchestrator-wavestack

- job:
    name: testbed-upgrade-cleura
    parent: testbed-upgrade
    vars:
      testbed_environment: cleura
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-upgrade-pco
    parent: testbed-upgrade
    vars:
      testbed_environment: pluscloudopen
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-upgrade-wavestack
    parent: testbed-upgrade
    vars:
      testbed_environment: wavestack
    nodeset: testbed-orchestrator-wavestack

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy
        - testbed-deploy-stable
        - testbed-upgrade
    gate:
      jobs:
        - tox-docs
        - tox-linters
        - testbed-deploy:
            branches: main
        - testbed-deploy-stable:
            branches: main
    post:
      jobs:
        - osism-publish-tox-docs-production:
            branches: main
    periodic-daily:
      jobs:
        - testbed-deploy
        - testbed-deploy-stable
        - testbed-deploy-cleura
        - testbed-deploy-pco
        - testbed-deploy-wavestack
        - testbed-deploy-wavestack-zed
        - testbed-upgrade
        - testbed-upgrade-cleura
        - testbed-upgrade-pco
        - testbed-upgrade-wavestack
