---
# Betacloud
- nodeset:
    name: testbed-orchestrator
    nodes:
      - name: orchestrator
        label: testbed-orchestrator

# Cleura
- nodeset:
    name: testbed-orchestrator-cleura
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-cleura

# PCO
- nodeset:
    name: testbed-orchestrator-pco
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-pco

# Wavestack
- nodeset:
    name: testbed-orchestrator-wavestack
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-wavecon

- job:
    name: testbed-deploy
    parent: base-extra-logs
    pre-run: playbooks/pre.yml
    nodeset: testbed-orchestrator
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    cleanup-run: playbooks/cleanup.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^\.github/.*$
      - ^doc/.*$
    timeout: 10800

- job:
    name: testbed-upgrade
    parent: testbed-deploy
    run: playbooks/upgrade.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    nodeset: testbed-orchestrator

- job:
    name: testbed-deploy-stable
    parent: testbed-deploy
    vars:
      docker_namespace_kolla: "kolla/release"
      manager_version: "5.3.0"
      refstack: true
    nodeset: testbed-orchestrator

- job:
    name: testbed-upgrade-stable
    parent: testbed-deploy
    run: playbooks/upgrade-stable.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    vars:
      docker_namespace_kolla: "kolla/release"
      docker_namespace_kolla_next: "kolla/release"
      manager_version: 4.3.0
      manager_version_next: 5.3.0
    nodeset: testbed-orchestrator

- job:
    name: testbed-update-stable
    parent: testbed-deploy
    run: playbooks/upgrade-stable.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    vars:
      docker_namespace_kolla: "kolla/release"
      docker_namespace_kolla_next: "kolla"
      manager_version: 5.3.0
      # NOTE: Update to the rolling tag to always ensure that an update to
      #       the next release will be possible.
      manager_version_next: latest
      # NOTE: Make sure that the Ceph and OpenStack version does not change
      #       when we go to the latest tag of the manager. This can happen
      #       if we have already switched to the next OpenStack release by
      #       default in latest, for example. As long as we are still working
      #       with the major releases this has to stay here.
      ceph_version_next: quincy
      openstack_version_next: zed
    nodeset: testbed-orchestrator

- job:
    name: testbed-upgrade-ceph
    parent: testbed-upgrade
    run: playbooks/upgrade-ceph.yml

- job:
    name: testbed-deploy-ceph
    parent: testbed-deploy
    run: playbooks/deploy-ceph.yml

- job:
    name: testbed-deploy-cleura
    parent: testbed-deploy
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-deploy-pco
    parent: testbed-deploy
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-deploy-wavestack
    parent: testbed-deploy
    nodeset: testbed-orchestrator-wavestack

- job:
    name: testbed-upgrade-cleura
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-upgrade-pco
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-upgrade-wavestack
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-wavestack

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
        - testbed-deploy
        - testbed-deploy-ceph
        - testbed-deploy-stable
        - testbed-update-stable
        - testbed-upgrade
        - testbed-upgrade-ceph
        - testbed-upgrade-stable
    gate:
      jobs:
        - ansible-lint
        - yamllint
        - flake8
        - testbed-deploy:
            branches: main
        - testbed-deploy-stable:
            branches: main
    post:
      jobs:
        - testbed-deploy-stable
    periodic-daily:
      jobs:
        - testbed-deploy
        - testbed-deploy-cleura
        - testbed-deploy-pco
        - testbed-deploy-stable
        - testbed-deploy-wavestack
        - testbed-update-stable
        - testbed-upgrade
        - testbed-upgrade-cleura
        - testbed-upgrade-pco
        - testbed-upgrade-stable
        - testbed-upgrade-wavestack
        - ansible-lint
        - yamllint
        - flake8

