---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-docs
        - tox-linters
    gate:
      jobs:
        - tox-docs
        - tox-linters
    post:
      jobs:
        - osism-publish-tox-docs-production:
            branches: main
