---
# Regiocloud
- nodeset:
    name: testbed-orchestrator
    nodes:
      - name: orchestrator
        label: testbed-orchestrator

- semaphore:
    name: semaphore-testbed
    max: 4

- job:
    name: abstract-testbed-deploy
    abstract: true
    parent: base-extra-logs
    semaphores:
      - name: semaphore-testbed
    pre-run: playbooks/pre.yml
    nodeset: testbed-orchestrator
    run: playbooks/deploy.yml
    post-run:
      - playbooks/post.yml
      - name: playbooks/cleanup.yml
        cleanup: true
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
      - osism/terraform-base
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^\.github/.*$
      - ^netbox/.*$
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explicitly bumped in the tenant configuration
    timeout: 16200
    vars:
      terraform_blueprint: testbed-default

- job:
    name: testbed-deploy
    parent: abstract-testbed-deploy
    vars:
      tempest: true
      prometheus_alert_status: false

- job:
    name: abstract-testbed-deploy-in-a-nutshell
    abstract: true
    parent: abstract-testbed-deploy
    vars:
      nutshell: true

- job:
    name: testbed-deploy-in-a-nutshell-ubuntu-24.04
    parent: abstract-testbed-deploy-in-a-nutshell
    vars:
      terraform_environment: ci-ubuntu-24.04

- job:
    name: testbed-deploy-in-a-nutshell-debian-12
    parent: abstract-testbed-deploy-in-a-nutshell
    vars:
      terraform_environment: ci-debian-12

- job:
    name: testbed-deploy-in-a-nutshell-centos-stream-9
    parent: abstract-testbed-deploy-in-a-nutshell
    vars:
      terraform_environment: ci-centos-stream-9

- job:
    name: testbed-deploy-in-a-nutshell-with-tempest-ubuntu-24.04
    parent: testbed-deploy-in-a-nutshell-ubuntu-24.04
    vars:
      tempest: true

- job:
    name: abstract-testbed-deploy-stable-in-a-nutshell
    abstract: true
    parent: abstract-testbed-deploy-in-a-nutshell
    vars:
      manager_version: 9.5.0

- job:
    name: testbed-deploy-stable-in-a-nutshell-ubuntu-24.04
    parent: abstract-testbed-deploy-stable-in-a-nutshell
    vars:
      terraform_environment: ci-ubuntu-24.04

- job:
    name: testbed-deploy-stable-in-a-nutshell-debian-12
    parent: abstract-testbed-deploy-stable-in-a-nutshell
    vars:
      terraform_environment: ci-debian-12

- job:
    name: testbed-deploy-stable-in-a-nutshell-centos-stream-9
    parent: abstract-testbed-deploy-stable-in-a-nutshell
    vars:
      terraform_environment: ci-centos-stream-9

- job:
    name: testbed-deploy-stable-in-a-nutshell-with-tempest-ubuntu-24.04
    parent: testbed-deploy-stable-in-a-nutshell-ubuntu-24.04
    vars:
      tempest: true

- job:
    name: testbed-deploy-current-in-a-nutshell-ubuntu-24.04
    parent: testbed-deploy-in-a-nutshell-ubuntu-24.04
    vars:
      ceph_version: reef
      openstack_version: "2024.2"

- job:
    name: testbed-deploy-next-in-a-nutshell-ubuntu-24.04
    parent: testbed-deploy-in-a-nutshell-ubuntu-24.04
    vars:
      ceph_version: reef
      openstack_version: "2025.1"

- job:
    name: testbed-deploy-current-in-a-nutshell-with-tempest-ubuntu-24.04
    parent: testbed-deploy-current-in-a-nutshell-ubuntu-24.04
    vars:
      tempest: true

- job:
    name: testbed-deploy-next-in-a-nutshell-with-tempest-ubuntu-24.04
    parent: testbed-deploy-next-in-a-nutshell-ubuntu-24.04
    vars:
      tempest: true

- job:
    name: testbed-upgrade
    parent: abstract-testbed-deploy
    run: playbooks/upgrade.yml
    timeout: 30000

- job:
    name: abstract-testbed-deploy-stable
    parent: abstract-testbed-deploy
    vars:
      manager_version: 9.5.0
      tempst: true
      prometheus_alert_status: false

- job:
    name: testbed-deploy-stable-ubuntu-24.04
    parent: abstract-testbed-deploy-stable
    vars:
      terraform_environment: ci-ubuntu-24.04

- job:
    name: testbed-deploy-stable-centos-stream-9
    parent: abstract-testbed-deploy-stable
    vars:
      terraform_environment: ci-centos-stream-9

- job:
    name: testbed-deploy-stable-debian-12
    parent: abstract-testbed-deploy-stable
    vars:
      terraform_environment: ci-debian-12

- job:
    name: abstract-testbed-update-stable
    parent: abstract-testbed-deploy
    run: playbooks/upgrade-stable.yml
    vars:
      manager_version: 9.4.0
      manager_version_next: 9.5.0
    nodeset: testbed-orchestrator
    timeout: 30000

- job:
    name: abstract-testbed-upgrade-stable
    parent: abstract-testbed-deploy
    run: playbooks/upgrade-stable.yml
    vars:
      manager_version: 8.1.0
      manager_version_next: 9.5.0
    nodeset: testbed-orchestrator
    timeout: 30000

- job:
    name: testbed-update-stable-ubuntu-24.04
    parent: abstract-testbed-update-stable
    vars:
      terraform_environment: ubuntu-24.04

- job:
    name: testbed-upgrade-stable-ubuntu-24.04
    parent: abstract-testbed-upgrade-stable
    vars:
      terraform_environment: ubuntu-24.04

- job:
    name: testbed-update-stable-next-ubuntu-24.04
    parent: abstract-testbed-deploy
    run: playbooks/update-stable.yml
    vars:
      manager_version: 9.5.0
      ceph_version_next: skip
      manager_version_next: latest
      openstack_version_next: "2024.2"
    nodeset: testbed-orchestrator
    timeout: 30000

# - job:
#     name: testbed-upgrade-stable-debian-12
#     parent: abstract-testbed-upgrade-stable
#     vars:
#       terraform_environment: debian-12

# - job:
#     name: testbed-upgrade-stable-centos-stream-9
#     parent: abstract-testbed-upgrade-stable
#     vars:
#       terraform_environment: centos-stream-9

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - flake8
        - python-black
        - yamllint
    label:
      jobs:
        - testbed-deploy-current-in-a-nutshell-ubuntu-24.04
        - testbed-deploy-next-in-a-nutshell-ubuntu-24.04
        - testbed-deploy-stable-in-a-nutshell-ubuntu-24.04
    label-additional:
      jobs:
        - testbed-update-stable-next-ubuntu-24.04
    periodic-midnight:
      jobs:
        - testbed-deploy-current-in-a-nutshell-with-tempest-ubuntu-24.04
        - testbed-deploy-next-in-a-nutshell-with-tempest-ubuntu-24.04
        - testbed-deploy-stable-in-a-nutshell-with-tempest-ubuntu-24.04
        - testbed-update-stable-next-ubuntu-24.04
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - python-black
        - yamllint
