---
# Betacloud
- nodeset:
    name: testbed-orchestrator
    nodes:
      - name: orchestrator
        label: testbed-orchestrator

# Cleura
- nodeset:
    name: testbed-orchestrator-cleura
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-cleura

# PCO
- nodeset:
    name: testbed-orchestrator-pco
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-pco

# Wavestack
- nodeset:
    name: testbed-orchestrator-wavestack
    nodes:
      - name: orchestrator
        label: testbed-orchestrator-wavecon

- job:
    name: testbed-deploy
    parent: base-extra-logs
    pre-run: playbooks/pre.yml
    nodeset: testbed-orchestrator
    run: playbooks/deploy.yml
    post-run: playbooks/post.yml
    cleanup-run: playbooks/cleanup.yml
    required-projects:
      - osism/ansible-collection-commons
      - osism/ansible-collection-services
      - osism/testbed
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$
      - ^doc/.*$
    timeout: 10800

- job:
    name: testbed-upgrade
    parent: testbed-deploy
    run: playbooks/upgrade.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    nodeset: testbed-orchestrator

- job:
    name: testbed-deploy-stable
    parent: testbed-deploy
    vars:
      manager_version: "5.0.0c"
      refstack: true
    nodeset: testbed-orchestrator

- job:
    name: testbed-upgrade-stable
    parent: testbed-deploy
    run: playbooks/upgrade-stable.yml
    # NOTE(frickler): Default zuul maximum timeout is 3h, this needs to
    # be explictly bumped in the tenant configuration
    timeout: 16200
    vars:
      manager_version: 4.2.0
      manager_version_next: 5.0.0c
    nodeset: testbed-orchestrator

- job:
    name: testbed-upgrade-ceph
    parent: testbed-upgrade
    run: playbooks/upgrade-ceph.yml

- job:
    name: testbed-deploy-ceph
    parent: testbed-deploy
    run: playbooks/deploy-ceph.yml

- job:
    name: testbed-deploy-cleura
    parent: testbed-deploy
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-deploy-pco
    parent: testbed-deploy
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-deploy-wavestack
    parent: testbed-deploy
    nodeset: testbed-orchestrator-wavestack

- job:
    name: testbed-upgrade-cleura
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-cleura

- job:
    name: testbed-upgrade-pco
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-pco

- job:
    name: testbed-upgrade-wavestack
    parent: testbed-upgrade
    nodeset: testbed-orchestrator-wavestack

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - ansible-lint
        - yamllint
        - flake8
        - testbed-deploy
        - testbed-deploy-ceph
        - testbed-deploy-stable
        - testbed-upgrade
        - testbed-upgrade-ceph
        - testbed-upgrade-stable
    gate:
      jobs:
        - tox-linters
        - ansible-lint
        - yamllint
        - flake8
        - testbed-deploy:
            branches: main
        - testbed-deploy-stable:
            branches: main
    post:
      jobs:
        - testbed-deploy-stable
    periodic-daily:
      jobs:
        - testbed-deploy
        - testbed-deploy-cleura
        - testbed-deploy-pco
        - testbed-deploy-stable
        - testbed-deploy-wavestack
        - testbed-upgrade
        - testbed-upgrade-cleura
        - testbed-upgrade-pco
        - testbed-upgrade-stable
        - testbed-upgrade-wavestack
