---
- secret:
    name: SECRET_TESTBED
    data:
      MANAGERLESS_CREDENTIALS: !encrypted/pkcs1-oaep
        - bO64XOE4Kp7QHYTKtfglNOb5AKyrjrZBxTU6kUKEdubpLfw+esnOJeCJhFPCHpM1fqVnW
          tgDItSDylvUl/QRYJvoRbNwMg/cDtLprSC2bRVwUdFDspyfIbJgvzOR/xXTne+kt669U4
          97rzRuE/+v/iwibmGG5cxd1kdhNH1fr/SuBhL71nzPDxc8NFqdNXAyLCc7778fgQxlWJ2
          q6fORFSl/u0qe1hG+PbpAPu9M5VzrQuub1owIfeYFL4d4aHYIFZTmo10IAH/ZwwpPhppZ
          KP2VpQ7MJiQF+5SUQn41kr3Yz5LNmKwoQnHlg4M41iTwLet1ywZImPHovE+oeWI/o6aGW
          aiyputgos5kAdpFrk9Gbk/XaUBx4wwymfUXpEr0iwuYU355poVKTizARVMT2sXgmngJOO
          34p1UqaOVIJgIR4f/4t0g/bqdhZ5gZl0899U6hCOKgLit0hIq4tqBVJaj6NfLFeu5rmWk
          PSIcrPfC2Uidm9ScxoROthIGuH6IQI9yEDJJeu6ilaxT05zUK0cJfudS3DTgiS7xi4WVC
          wOGFj3DlmJ6CiCVXiaSvNIYULz6gMBcHSTnma+1hm2aUcrF6eoOdAwiNl6qp4+pmkKaJu
          tiQco0DrJncvqhRNiNNBFJbipoDl2r28W2kSWnobr2mo4Jb7crUaS1jDxh5q1o=

- semaphore:
    name: semaphore-testbed-managerless
    max: 1

- job:
    name: testbed-deploy-managerless
    nodeset: ubuntu-jammy
    pre-run: playbooks/managerless/pre.yml
    run: playbooks/managerless/deploy.yml
    post-run: playbooks/managerless/post.yml
    required-projects:
      - osism/terraform-base
    timeout: 10800
    vars:
      terraform_blueprint: testbed-managerless
      cloud_env: managerless-otc
    secrets:
      - name: secret
        secret: SECRET_TESTBED
    semaphores:
      - name: semaphore-testbed-managerless

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - ansible-lint
    post:
      jobs:
        - testbed-deploy-managerless
    periodic-hourly-otc:
      jobs:
        - ansible-lint
        - flake8
#        - testbed-deploy-managerless
#        - python-black
#        - yamllint
