---
# A set of parameters that works on CityNetwork's public cloud
# (CityCloud), tested successfully on the fra1 region.
# Beware of quota limits (50GB RAM is just not enough).
parameter_defaults:
  availability_zone: nova
  volume_availability_zone: nova
  flavor_node: 4C-16GB-50GB
  flavor_manager: 2C-4GB-20GB
  image: Ubuntu 18.04 Bionic Beaver 20190724.1
  public: ext-net
  volume_size_storage: 12
  ceph_version: nautilus
  openstack_version: train
