---
- name: Manage sites and locations
  connection: local
  hosts: localhost
  gather_facts: false

  collections:
    - netbox.netbox

  tasks:
    - name: Manage Discworld site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: Discworld
          slug: discworld
        state: present

    - name: Manage Ankh-Morpork location
      netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: Ankh-Morpork
          slug: ankh-morpork
          site: discworld
        state: present
