---
# A set of parameters that works on CityNetwork's public cloud
# (CityCloud), tested successfully on the fra1 region.
# Beware of quota limits (50GB RAM is just not enough).
parameter_defaults:
  availability_zone: nova
  volume_availability_zone: nova
  network_availability_zone: nova
  flavor_node: 8C-32GB-150GB
  flavor_manager: 4C-4GB-50GB
  image: Ubuntu 18.04 Bionic Beaver
  public: ext-net
  volume_size_storage: 10
  ceph_version: nautilus
  openstack_version: train
  configuration_version: master
