---
node_id: 1

##########################################################
# ansible

ansible_host: "{{ '192.168.16.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"

##########################################################
# netbox

netbox_inventory_status: Active

##########################################################
# generic

console_interface: "{{ ansible_local.testbed_network_devices.management }}"
management_interface: "{{ ansible_local.testbed_network_devices.internal }}"

internal_address: "{{ '192.168.32.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
fluentd_host: "{{ '192.168.32.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"

##########################################################
# cockpit

configure_cockpit_server: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ ansible_local.testbed_network_devices.management }}"

##########################################################
# netdata

netdata_host_type: client

##########################################################
# network

network_allow_service_restart: false
network_restart_method: nothing

network_interfaces:
  - device: "{{ ansible_local.testbed_network_devices.management }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.16.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    gateway: "{{ '192.168.16.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr('1') | ansible.netcommon.ipaddr('address') }}"
    mtu: 1450
    up:
      - "ip route add 192.168.48.0/20 via {{ '192.168.32.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr('5') | ansible.netcommon.ipaddr('address') }}"
    down:
      - "ip route del 192.168.48.0/20 via {{ '192.168.32.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr('5') | ansible.netcommon.ipaddr('address') }}"

  - device: "{{ ansible_local.testbed_network_devices.internal }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.32.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: 1450

  - device: "{{ ansible_local.testbed_network_devices.external }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.96.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: 1450

  - device: "{{ ansible_local.testbed_network_devices.provider }}"
    auto: true
    family: inet
    method: manual
    mtu: 1450

  - device: "{{ ansible_local.testbed_network_devices.storage_frontend }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.64.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: 1450

  - device: "{{ ansible_local.testbed_network_devices.storage_backend }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.80.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: 1450

  - device: ohm0
    method: static
    address: "{{ '192.168.128.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: 1300
    up:
      - "ip link set dev ohm0 address 02:00:00:00:00:{{ 10 + node_id }}"
      - iptables -I INPUT -i ohm0 -p udp --dport 5555 -j ACCEPT

##########################################################
# kolla

network_interface: "{{ ansible_local.testbed_network_devices.internal }}"

# api_interface:
# dns_interface:
kolla_external_vip_interface: "{{ ansible_local.testbed_network_devices.external }}"
# migration_interface:
neutron_external_interface: "{{ ansible_local.testbed_network_devices.provider }}"
# octavia_network_interface:
storage_interface: "{{ ansible_local.testbed_network_devices.storage_frontend }}"
# tunnel_interface:

##########################################################
# ceph

# monitor_interface:
monitor_address: "{{ '192.168.64.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"
# radosgw_interface:
radosgw_address: "{{ '192.168.64.0/20' | ansible.netcommon.ipaddr('net') | ansible.netcommon.ipaddr(10 + node_id) | ansible.netcommon.ipaddr('address') }}"

devices: "{{ ansible_local.testbed_ceph_devices }}"

# NOTE: to use the third block device for Ceph change this parameter as follows
# devices: "{{ ansible_local.testbed_ceph_devices_all }}"
