---
##########################################################
# ansible

ansible_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"

##########################################################
# netbox

netbox_inventory_status: Active

##########################################################
# generic

console_interface: "{{ ansible_local.testbed_network_devices.management }}"
management_interface: "{{ ansible_local.testbed_network_devices.internal }}"

internal_address: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
fluentd_host: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"

##########################################################
# cockpit

configure_cockpit_server: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ ansible_local.testbed_network_devices.management }}"

##########################################################
# netdata

netdata_host_type: client

##########################################################
# network

network_interfaces:
  - device: "{{ ansible_local.testbed_network_devices.management }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
    netmask: 255.255.240.0
    gateway: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
    mtu: "{{ testbed_mtu }}"
    up:
      - "ip route add 192.168.48.0/20 via {{ '192.168.32.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    down:
      - "ip route del 192.168.48.0/20 via {{ '192.168.32.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"

  - device: "{{ ansible_local.testbed_network_devices.internal }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.external }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.96.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.provider }}"
    auto: true
    family: inet
    method: manual
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.storage_frontend }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.64.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.storage_backend }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.80.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

##########################################################
# kolla

network_interface: "{{ ansible_local.testbed_network_devices.internal }}"

# api_interface:
# dns_interface:
kolla_external_vip_interface: "{{ ansible_local.testbed_network_devices.external }}"
# migration_interface:
neutron_external_interface: "{{ ansible_local.testbed_network_devices.provider }}"
# octavia_network_interface:
storage_interface: "{{ ansible_local.testbed_network_devices.storage_frontend }}"
# tunnel_interface:

##########################################################
# ceph

# monitor_interface:
monitor_address: "{{ '192.168.64.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"
# radosgw_interface:
radosgw_address: "{{ '192.168.64.0/20' | ipaddr('net') | ipaddr(11) | ipaddr('address') }}"

devices: "{{ ansible_local.testbed_ceph_devices }}"

# NOTE: to use the third block device for Ceph change this parameter as follows
# devices: "{{ ansible_local.testbed_ceph_devices_all }}"
