---
node_id: 5

##########################################################
# ansible

ansible_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(5) | ipaddr('address') }}"

##########################################################
# netbox

netbox_inventory_status: Active

##########################################################
# generic

console_interface: "{{ ansible_local.testbed_network_devices.management }}"
management_interface: "{{ ansible_local.testbed_network_devices.management }}"

internal_address: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(5) | ipaddr('address') }}"
fluentd_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(5) | ipaddr('address') }}"

##########################################################
# cockpit

configure_cockpit_server: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ ansible_local.testbed_network_devices.management }}"

##########################################################
# docker

docker_allow_restart: false

##########################################################
# netdata

netdata_host_type: server

##########################################################
# network

network_type: netplan
network_ethernets:
  "{{ ansible_local.testbed_network_devices.management }}":
    addresses:
      - "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}/20"
      - "{{ '192.168.64.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}/20"
      - "{{ '192.168.96.0/20' | ipaddr('net') | ipaddr(node_id) | ipaddr('address') }}/20"
    gateway4: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
    mtu: "{{ testbed_mtu_manager }}"
network_dispatcher_scripts:
  - src: /opt/configuration/network/vxlan.sh
    dest: routable.d/vxlan.sh
  - src: /opt/configuration/network/iptables.sh
    dest: routable.d/iptables.sh

##########################################################
# kolla

network_interface: "{{ ansible_local.testbed_network_devices.management }}"
