---
##########################################################
# ansible

ansible_host: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"

##########################################################
# netbox

netbox_inventory_status: Active

##########################################################
# generic

console_interface: "{{ ansible_local.testbed_network_devices.management }}"
management_interface: "{{ ansible_local.testbed_network_devices.internal }}"

internal_address: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
fluentd_host: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"

##########################################################
# cockpit

configure_cockpit_server: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ ansible_local.testbed_network_devices.management }}"

##########################################################
# netdata

netdata_host_type: server

##########################################################
# network

network_interfaces:
  - device: "{{ ansible_local.testbed_network_devices.management }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    netmask: 255.255.240.0
    gateway: "{{ '192.168.16.0/20' | ipaddr('net') | ipaddr('1') | ipaddr('address') }}"
    mtu: "{{ testbed_mtu }}"
    up:
      - "iptables -A FORWARD -i {{ ansible_local.testbed_network_devices.management }} -j ACCEPT"
      - "iptables -A FORWARD -o {{ ansible_local.testbed_network_devices.management }} -j ACCEPT"
      - "iptables -t nat -A POSTROUTING -o {{ ansible_local.testbed_network_devices.management }} -j MASQUERADE"

  - device: "{{ ansible_local.testbed_network_devices.internal }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.32.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.external }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.96.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.provider }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.112.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

  - device: "{{ ansible_local.testbed_network_devices.storage_frontend }}"
    auto: true
    family: inet
    method: static
    address: "{{ '192.168.64.0/20' | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
    netmask: 255.255.240.0
    mtu: "{{ testbed_mtu }}"

##########################################################
# kolla

network_interface: "{{ ansible_local.testbed_network_devices.internal }}"
