scrape_configs:
  - job_name: smart-exporter
    scrape_interval: 300s
    static_configs:
{% for host in groups['generic'] %}
      - targets:
        - "{{ hostvars[host]['ansible_facts'][hostvars[host]['network_interface']]['ipv4']['address'] }}:{{ smart_exporter_port | default('9633') }}"
{% if hostvars[host].prometheus_instance_label | default(false, true) %}
        labels:
          instance: "{{ hostvars[host].prometheus_instance_label }}"
{% endif %}
{% endfor %}
