availability_zone         = "nova"
volume_availability_zone  = "nova"
network_availability_zone = "nova"
flavor_node               = "8C-32GB-150GB"
flavor_manager            = "4C-4GB-50GB"
image                     = "Ubuntu 18.04 Bionic Beaver"
public                    = "ext-net"
volume_size_storage       = "10"
