availability_zone         = "nova"
volume_availability_zone  = "nova"
network_availability_zone = "nova"
flavor_node               = "4C-16GB-50GB"
flavor_manager            = "2C-4GB-20GB"
image                     = "Ubuntu 18.04 Bionic Beaver 20190724.1"
public                    = "ext-net"
volume_size_storage       = "12"
