availability_zone         = "nova"
volume_availability_zone  = "nova"
network_availability_zone = "nova"
flavor_node               = "4C-16GB-60GB"
flavor_manager            = "2C-4GB-20GB"
image                     = "cloud-ubuntu-1804"
public                    = "provider"
volume_size_storage       = "10"
