---
required_packages_extra:
  # The correct package name is linux-generic-hwe-22.04 on Ubuntu 22.04
  # and linux-generic-hwe-24.04 on Ubuntu 24.04.
  - "linux-generic-hwe-{{ ansible_distribution_version }}"
