---
- name: Manage device configuration
  hosts: all

  tasks:
    - name: Check that the configuration exists
      stat:
        path: "/state/{{ device }}.cfg.j2"
      register: result

    - name: Fail, if it configuration does not exist
      fail:
        msg: "The configuration for device {{ device }} does not exist"
      when: not result.stat.exists

    - name: Simulate the rendering of the configuration
      set_fact:
        configuration: "{{ lookup('template', '/state/{{ device }}.cfg.j2') }}"

    - name: Output the rendered configuration
      debug:
        msg: "{{ configuration }}"
