---
# NOTE: To ensure that the Netbox is fully initialized during
#       initialization, regardless of the Ansibler runtime
#       environments and python-osism, the /metrics endpoint
#       is checked. The /metrics endpoint can only be accessed
#       once the Netbox has been initialized and is accessible
#       via Traefik.

- name: Wait for netbox service
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for netbox service
      ansible.builtin.uri:
        url: "{{ netbox_url }}/metrics"
        return_content: true
        status_code: [200]
        validate_certs: false
      register: result
      failed_when: "'python_info' not in result.content"
      retries: 60
      delay: 5

- name: Manage sites and locations
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Manage Discworld site
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: Discworld
          slug: discworld
        state: present

    - name: Manage Ankh-Morpork location
      netbox.netbox.netbox_location:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: Ankh-Morpork
          slug: ankh-morpork
          site: discworld
        state: present

- name: Manage IP prefixes
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Manage 192.168.16.0/20
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          family: 4
          prefix: 192.168.16.0/20
          prefix_role: Management
        state: present

    - name: Manage 192.168.112.0/20
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          family: 4
          prefix: 192.168.112.0/20
          prefix_role: External
        state: present

- name: Manage IP addresses
  connection: local
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Manage api.testbed.osism.xyz IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: 192.168.16.254
          dns_name: api.testbed.osism.xyz
        state: present

    - name: Manage api-int.testbed.osism.xyz IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          address: 192.168.16.9
          dns_name: api-int.testbed.osism.xyz
        state: present
