---
sources:
  - name: meter_source
    meters:
      - "*"
    sinks:
      - meter_sink
sinks:
  - name: meter_sink
    publishers:
      - prometheus://testbed-manager-0.testbed.osism.xyz/metrics/job/openstack-telemetry
