{
 "title": "OpenStack Dashboard",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nova agents down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})-sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 3, "y": 1 },
   "targets": [
    { "expr": "openstack_nova_agent_state" }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 3, "y": 9 },
   "targets": [
    { "expr": "openstack_neutron_agent_state" }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Cinder agents down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(count(openstack_cinder_agent_state{adminState=\"enabled\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\"}))"
    }
   ]
  },
  {
   "title": "Cinder agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 3, "y": 17 },
   "targets": [
    { "expr": "openstack_cinder_agent_state" }
   ]
  },
  {
   "title": "Cinder agent up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(openstack_cinder_agent_state{adminState=\"enabled\"})"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Overall memory usage (TiB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Memory in TiB" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes)",
     "legendFormat": "memory in use"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes)",
     "legendFormat": "memory available"
    }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    { "expr": "sum(openstack_nova_vcpus_used)", "legendFormat": "used vcpu cores" },
    {
     "expr": "sum(openstack_nova_vcpus_available)",
     "legendFormat": "total vcpu cores"
    }
   ]
  },
  {
   "title": "Local Storage (TB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_local_storage_used_bytes)",
     "legendFormat": "local storage used"
    },
    {
     "expr": "sum(openstack_nova_local_storage_available_bytes)",
     "legendFormat": "local storage available"
    }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks)",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups)",
     "legendFormat": "security groups"
    },
    { "expr": "avg(openstack_neutron_subnets)", "legendFormat": "subnets" }
   ]
  },
  {
   "title": "Keystone stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(openstack)", "legendFormat": "projects" },
    { "expr": "avg(openstack_identity_users)", "legendFormat": "users" },
    { "expr": "avg(openstack_identity_groups)", "legendFormat": "groups" }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms)",
     "legendFormat": "running vms"
    },
    { "expr": "sum(openstack_nova_total_vms)", "legendFormat": "total vms" }
   ]
  },
  {
   "title": "Cinder volumes/snapshots",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(openstack_cinder_volumes)", "legendFormat": "volumes" },
    {
     "expr": "avg(openstack_cinder_snapshots)",
     "legendFormat": "snapshots"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(openstack_glance_images)", "legendFormat": "images" }
   ]
  }
 ]
}