{
 "title": "Redfish exporter",
 "time": { "from": "now-30m", "to": "now-5m" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "label_values(redfish_exporter_collector_duration_seconds, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "iDRAC Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"redfish-exporter\"} == 1)"
    },
    {}
   ]
  },
  {
   "title": "Powered On",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(redfish_system_power_state == 1)"
    }
   ]
  },
  {
   "title": "Powered Off",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(redfish_system_power_state != 1)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(redfish_chassis_health != 1)"
    }
   ]
  },
  {
   "title": "Nodes with SEL Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count(redfish_logservices_entry_count{name=\"SEL Log Service\", severity!=\"OK\"} != 0)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(redfish_chassis_power_average_consumed_watts)",
     "legendFormat": "Rack power consumption"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(redfish_chassis_power_average_consumed_watts) by (env)",
     "legendFormat": "{{ env }}"
    }
   ]
  },
  {
   "title": "Power states",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "sort_desc(redfish_system_power_state)"
    }
   ]
  },
  {
   "title": "Chassis status",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "targets": [
    { "expr": "sort(redfish_chassis_health)" }
   ]
  },
  {
   "title": "Max Inlet Temp",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(redfish_chassis_temperature_celsius{sensor_id=~\".*InletTemp\"}) by (env)",
     "legendFormat": "max inlet {{ env }}"
    }
   ]
  },
  {
   "title": "Max CPU1 Temp",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 5, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(redfish_chassis_temperature_celsius{sensor_id=~\".*CPU1Temp\"}) by (env)",
     "legendFormat": "{{ env }}"
    }
   ]
  },
  {
   "title": "Max CPU2 Temp",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(redfish_chassis_temperature_celsius{sensor_id=~\".*CPU2Temp\"}) by (env)",
     "legendFormat": "{{ env }}"
    }
   ]
  },
  {
   "title": "Powered ON by Rack",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redfish_system_power_state == 1) by (env)",
     "legendFormat": "Powered up {{ env }}"
    }
   ]
  },
  {
   "title": "Powered OFF by Rack",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(redfish_system_power_state == 2) by (env)",
     "legendFormat": "Powered down {{ env }}"
    }
   ]
  },
  {
   "title": "Max Inlet Temp",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*InletTemp\"}"
    }
   ]
  },
  {
   "title": "Max server fan speed",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "max(redfish_chassis_fan_rpm_percentage) by (server) > 0"
    }
   ]
  },
  {
   "title": "CPU1 Temp",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*CPU1Temp\"} != 0",
     "legendFormat": "{{ env }}"
    }
   ]
  },
  {
   "title": "CPU2 Temp",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*CPU2Temp\"} != 0",
     "legendFormat": "{{ env }}"
    }
   ]
  },
  {
   "title": "Max Inlet Temp",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*InletTemp\"}",
     "legendFormat": "{{ env }} {{ server }}"
    }
   ]
  },
  {
   "title": "Max CPU1 Temp",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{sensor_id=~\".*CPU1Temp\"} != 0",
     "legendFormat": "{{ env }} {{ server }}"
    }
   ]
  },
  {
   "title": "Errors in event log",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sort(redfish_logservices_entry_count{name=\"SEL Log Service\", severity!=\"OK\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }, "repeat": "server" },
  {
   "title": "Power comsumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_power_average_consumed_watts{server=~\"$server\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(redfish_system_storage_drive_state{server=~\"$server\"} != 1) or vector(0)"
    }
   ]
  },
  {
   "title": "PCI-E with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(redfish_system_pcie_device_health_state{server=~\"$server\"} != 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Sensors with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(redfish_chassis_temperature_sensor_state{server=~\"$server\"} != 1) or vector(0)"
    }
   ]
  },
  {
   "title": "PS with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "count(redfish_chassis_power_powersupply_health{server=~\"$server\"} > 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{server=~\"$server\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_system_power_state{server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "General Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_chassis_health{server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "BMC Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_manager_health_state{server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "redfish_chassis_fan_rpm_percentage{server=~\"$server\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{server=~\"$server\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk states / health",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "redfish_system_storage_drive_state{server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Power comsumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_chassis_power_average_consumed_watts{server=~\"$server\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}