#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

cat playbooks/diskimage.yml > $TMP_HOOKS_PATH/diskimage.yml
