[DEFAULT]
# The use of these paraemters in production is not recommended. Further details in OSSN-0090.
# https://wiki.openstack.org/wiki/OSSN/OSSN-0090
show_multiple_locations = True
show_image_direct_url = True

[taskflow_executor]
conversion_format = raw

[image_import_opts]
image_import_plugins = ['image_decompression', 'image_conversion']

[image_conversion]
output_format = raw
