---
- name: Cleanup after bootstrap
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Set python3 as default
      command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1  # noqa 301
      become: true

    # NOTE: This must be the last task. It will uninstall Ansible.
    - name: Purge python2 environment
      apt:
        name: python
        state: absent
        autoremove: true
        purge: true
      become: true
