---
- name: Copy custom facts
  hosts: testbed-manager.osism.test
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install required packages
      become: true
      apt:
        name: python3-netifaces
        state: present

    - name: Create custom facts directory
      become: true
      file:
        path: /etc/ansible/facts.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy fact files
      become: true
      copy:
        src: /opt/configuration/environments/custom/files/testbed_network_devices.fact
        dest: /etc/ansible/facts.d/testbed_network_devices.fact
        owner: root
        group: root
        mode: 0755

- name: Apply role manager & netbox
  hosts: testbed-manager.osism.test
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_registry_ansible: quay.io

  vars_files:
    - /opt/configuration/inventory/host_vars/testbed-manager.osism.test.yml
    - /opt/configuration/environments/manager/configuration.yml
    - /opt/configuration/environments/manager/images.yml
    - /opt/configuration/environments/manager/secrets.yml
    - /opt/configuration/environments/secrets.yml

  collections:
    - osism.services

  roles:
    - netbox
    - manager
