---
- name: Copy custom facts
  hosts: testbed-manager.osism.test
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create custom facts directory
      file:
        path: /etc/ansible/facts.d
        state: "directory"
        owner: root
        group: root
        mode: 0755
      become: true

    - name: Copy fact files
      copy:
        src: "/opt/configuration/environments/custom/files/{{ item }}.fact"
        dest: "/etc/ansible/facts.d/{{ item }}.fact"
        owner: root
        group: root
        mode: 0755
      become: true
      loop:
        - testbed_ceph_devices
        - testbed_ceph_devices_all
        - testbed_network_devices

- name: Apply role manager
  hosts: testbed-manager.osism.test
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_registry_ansible: quay.io

  vars_files:
    - /opt/configuration/inventory/host_vars/testbed-manager.osism.test.yml
    - /opt/configuration/environments/manager/configuration.yml
    - /opt/configuration/environments/manager/images.yml
    - /opt/configuration/environments/manager/secrets.yml
    - /opt/configuration/environments/secrets.yml

  collections:
    - osism.services

  roles:
    - manager
