---
- name: Apply role docker
  hosts: testbed-manager.osism.local
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: yes
    docker_configure_storage_driver: yes
    docker_kata_install: yes
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_version: "5:19.03.5"

  roles:
    - ansible-docker

- name: Apply role docker-compose
  hosts: testbed-manager.osism.local
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  roles:
    - ansible-docker-compose
