---
- name: Apply role configuration
  hosts: testbed-manager.osism.test
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    configuration_git_host: github.com
    configuration_git_port: 443
    configuration_git_repository: osism/testbed.git
    configuration_git_protocol: https

  collections:
    - osism.commons

  roles:
    - role: configuration
