---
- name: Create operator user
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

  collections:
    - osism.commons

  roles:
    - role: operator
