---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # ansible-common
    cleanup_services_common:
      - NetworkManager
      - iscsid
      - lxcfs
      - nscd
      - ntp
    cleanup_packages_common:
      - apport
      - apport-symptoms
      - dosfstools
      - libvirt-bin
      - lxc
      - lxd
      - ntfs-3g
      - open-iscsi
      - popularity-contest
      - python3-apport
      - snapd
      - telnet
      - ubuntu-server
      - xauth
    rng_enable_common: yes
    smartd_enable_common: no
    upgrade_packages_common: no

    # ansible-operator
    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

    # ansible-repository
    repository_cache_valid_time: 0
    repository_key_ids: {}
    repositories:
      - name: "{{ ansible_distribution_release }}"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-backports"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-security"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-updates"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"

  collections:
    - osism.commons
    - osism.services

  roles:
    - role: resolvconf
    - role: chrony
    - role: repository
    - role: systohc
    - role: configfs
    - role: packages
    - role: sysctl
    - role: services
    - role: facts
    - role: motd
    - role: hddtemp
    - role: rng
    - role: smartd
    - role: cleanup
    - role: operator

- name: Apply role docker
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: yes
    docker_configure_storage_driver: yes
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_version: "5:19.03.13"

  collections:
    - osism.services

  roles:
    - docker

- name: Apply role docker_compose
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  collections:
    - osism.commons

  roles:
    - role: docker_compose
