availability_zone         = "nova"
volume_availability_zone  = "nova"
network_availability_zone = "nova"
flavor_node               = "8C-32GB-150GB"
flavor_manager            = "4C-8GB-50GB"
image                     = "Ubuntu 20.04 Focal Fossa 20200423"
public                    = "ext-net"
volume_size_storage       = "10"
