#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# install required ansible roles

ansible-galaxy install git+https://github.com/ANXS/apt
ansible-galaxy install git+https://github.com/ANXS/timezone
ansible-galaxy install git+https://github.com/ANXS/utilities
ansible-galaxy install git+https://github.com/osism/ansible-common
ansible-galaxy install git+https://github.com/osism/ansible-docker
ansible-galaxy install git+https://github.com/osism/ansible-operator
ansible-galaxy install git+https://github.com/osism/ansible-repository

# run ansible playbook

ansible-playbook -i localhost, /tmp/in_target.d/diskimage.yml

# cleanup

rm -rf /root/.ansible
