---
rook_network_public: 192.168.128.0/20

rook_storage_devicefilter: "^sd[b-c]"
rook_storage_nodes:
  - name: testbed-node-3
  - name: testbed-node-4
  - name: testbed-node-5

# reduce resources to fit into testbed
rook_resources_cephfilesystem:
  limits:
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "4Gi"
rook_resources_cephobjecstore:
  limits:
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

rook_dashboard:
  enabled: true
  port: 7000
  ssl: false

# set to true to enable monitoring
# rook_monitoring_enabled: true

# set to true to enable cleanup
# rook_cleanup: true
