---
- name: Create operator user
  hosts: all

  roles:
    - osism.commons.operator

- name: Deploy manager service
  hosts: all

  vars:
    # The parameterisation comes later from a central place.
    version_ceph: quincy
    version_manager: latest
    version_openstack: zed

  roles:
    - osism.services.manager
