---
- name: Deploy services
  hosts: all
  connection: local
  gather_facts: true

  tasks:
    - name: Run known-hosts
      ansible.builtin.command:
        cmd: osism apply known-hosts
      environment:
        INTERACTIVE: "false"
      changed_when: true

    - name: Deploy infrastructure services (sync)
      ansible.builtin.command:
        cmd: "osism apply {{ item }}"
      environment:
        INTERACTIVE: "false"
      changed_when: true
      loop:
        - common
        - loadbalancer
        - openvswitch

    # - name: Deploy infrastructure services (async)
    #   ansible.builtin.command:
    #     cmd: "osism apply {{ item }}"
    #   environment:
    #     INTERACTIVE: "false"
    #   changed_when: true
    #   loop:
    #     - memcached
    #     - redis
    #     - mariadb
    #     - rabbitmq
    #     - opensearch
    #     - ovn
    #   async: 600
    #   poll: 0
    #   register: async_results

    # - name: Check deployment of infrastructure services
    #   ansible.builtin.async_status:
    #     jid: "{{ async_result_item.ansible_job_id }}"
    #   loop: "{{ async_results.results }}"
    #   loop_control:
    #     loop_var: "async_result_item"
    #   register: async_poll_results
    #   until: async_poll_results.finished
    #   retries: 30
    #   delay: 20

    # - name: Deploy ceph services
    #   ansible.builtin.command:
    #     cmd: "osism apply {{ item }}"
    #   environment:
    #     INTERACTIVE: "false"
    #   changed_when: true
    #   loop:
    #     - ceph-base

    # - name: Get ceph keys
    #   ansible.builtin.command:
    #     cmd: "osism apply {{ item }}"
    #   environment:
    #     INTERACTIVE: "false"
    #   changed_when: true
    #   loop:
    #     - ceph-fetch-keys
    #     - copy-ceph-keys

    # - name: Deploy openstack services (sync)
    #   ansible.builtin.command:
    #     cmd: "osism apply {{ item }}"
    #   environment:
    #     INTERACTIVE: "false"
    #   changed_when: true
    #   loop:
    #     - keystone
    #     - placement
    #     - nova
    #     - neutron
    #     - horizon
    #     - glance
    #     - cinder
    #     - designate
    #     - octavia
