---
- name: Run local preparations
  hosts: localhost
  connection: local

  tasks:
    - name: Sync configuration with generics
      ansible.builtin.command:
        chdir: /opt/configuration
        cmd: gilt overlay
      changed_when: true

- name: Deploy required services
  hosts: localhost
  connection: local

  vars:
    docker_compose_install_type: package
    docker_facts: false
    docker_python_install: false

  roles:
    - role: osism.commons.timezone
    - role: osism.services.docker
    - role: osism.commons.docker_compose

- name: Copy custom facts
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create custom facts directory
      become: true
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy fact files
      become: true
      ansible.builtin.copy:
        src: /opt/configuration/environments/custom/files/testbed_network_devices.fact
        dest: /etc/ansible/facts.d/testbed_network_devices.fact
        owner: root
        group: root
        mode: 0755
