---
- name: Check local versions
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Fail if ansible-core version is lower than 2.13.0
      ansible.builtin.fail:
        msg: "Ansible core version is {{ ansible_version.full }}, see https://docs.scs.community/docs/testbed/doc/getting_started for required version."
      when: ansible_version.full < "2.13.0"

    - name: Get terraform version
      ansible.builtin.shell: >-
        set -o pipefail &&
        terraform --version | head -n1  | awk '{print $2}' | awk -Fv '{print $2}'
      register: result
      changed_when: false
      args:
        executable: /bin/bash

    - name: Fail if terraform version is lower than 1.2.0
      ansible.builtin.fail:
        msg: "Terraform version is {{ result.stdout }}, see https://docs.scs.community/docs/testbed/doc/getting_started for required version."
      when: result.stdout < "1.2.0"
