---
- name: Check local versions
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_core_version: "2.15.0"
    python_version: "3.10.0"
    terraform_version: "1.6.0"

  tasks:
    - name: "Fail if ansible-core version is lower than {{ ansible_core_version }}"
      ansible.builtin.fail:
        msg: "Ansible core version is {{ ansible_version.full }}, see https://osism.tech/docs/guides/other-guides/testbed/ for required version."
      when: ansible_version.full is ansible.builtin.version(ansible_core_version, '<')

    - name: Get terraform version
      ansible.builtin.shell: >-
        set -o pipefail &&
        tofu --version | head -n1 | awk '{print $2}' | awk -Fv '{print $2}'
      register: result
      changed_when: false
      args:
        executable: /bin/bash

    - name: "Fail if terraform version is lower than {{ terraform_version }}"
      ansible.builtin.fail:
        msg: "Terraform version is {{ result.stdout }}, see https://osism.tech/docs/guides/other-guides/testbed/ for required version."
      when: result.stdout is ansible.builtin.version(terraform_version, '<')

    - name: Get python version
      ansible.builtin.shell: >-
        set -o pipefail &&
        python3 --version | awk '{print $2}'
      register: result
      changed_when: false
      args:
        executable: /bin/bash

    - name: "Fail if python version is lower than {{ python_version }}"
      ansible.builtin.fail:
        msg: "Python version is {{ result.stdout }}, see https://osism.tech/docs/guides/other-guides/testbed/ for required version."
      when: result.stdout is ansible.builtin.version(python_version, '<')
