---
- name: Create test project
  hosts: localhost
  connection: local

  tasks:
    - name: Create domain-manager role
      openstack.cloud.identity_role:
        cloud: admin
        state: present
        name: domain-manager

    - name: Create test domain
      openstack.cloud.identity_domain:
        cloud: admin
        state: present
        name: test

    - name: Create test-admin user
      openstack.cloud.identity_user:
        cloud: admin
        state: present
        name: test-admin
        password: test
        email: test-admin@testbed.osism.xyz
        domain: default
      no_log: true

    # NOTE: The CLI is used here because the corresponding Ansible module does
    #       not find the test-admin user in the default domain.
    - name: Add domain-manager role to user test-admin
      ansible.builtin.command: openstack --os-cloud admin role add --domain test --user test-admin domain-manager
      changed_when: true

    - name: Create test project
      openstack.cloud.project:
        cloud: test-admin
        state: present
        name: test
        domain: test

    - name: Create test user
      openstack.cloud.identity_user:
        cloud: test-admin
        state: present
        name: test
        password: test
        email: test@testbed.osism.xyz
        domain: test
        default_project: test
      no_log: true

    - name: Add member role to user test
      openstack.cloud.role_assignment:
        cloud: test-admin
        state: present
        user: test
        role: member
        project: test
