---
- name: Setup s3 backups
  hosts: mariadb
  become: true
  gather_facts: false
  vars_files:
    - configuration.yml
    - secrets.yml
  vars:
    mariadb_s3_backup_rclone_docker_registry: "ghcr.io"
    mariadb_s3_backup_rclone_docker_image: "rclone/rclone"
    mariadb_s3_backup_rclone_docker_tag: "1.74.3"
    mariadb_s3_backup_rclone_image_full: "{{ mariadb_s3_backup_rclone_docker_registry }}/{{ mariadb_s3_backup_rclone_docker_image }}:{{ mariadb_s3_backup_rclone_docker_tag }}"

    mariadb_s3_backup_rclone_config_volume: "rclone-config"
    mariadb_s3_backup_rclone_s3_provider: "Ceph"
    mariadb_s3_backup_rclone_identifier: "backup"

    mariadb_s3_backup_s3_hostname: "api.bfe2.teutostack.de"
    mariadb_s3_backup_s3_port: "6780"
    mariadb_s3_backup_s3_endpoint: "https://{{ mariadb_s3_backup_s3_hostname}}:{{mariadb_s3_backup_s3_port}}"
    mariadb_s3_backup_s3_provider: "ceph"
    mariadb_s3_backup_s3_bucket: "mariadb-backups"
    mariadb_s3_backup_s3_virtual_hosted_style_bucket: false
    mariadb_s3_backup_s3_path: ""
    mariadb_s3_backup_s3_region: ""
    mariadb_s3_backup_s3_access_key_id: ""
    mariadb_s3_backup_s3_secret_access_key: ""
  tasks:
    - name: Pull images
      community.docker.docker_image_pull:
        name: "{{ item }}"
      loop:
        - "{{ mariadb_s3_backup_rclone_image_full }}"

    - name: Ensure directory exists
      ansible.builtin.file:
        state: "directory"
        path: "/etc/kolla/mariadb-s3-backup"
        mode: "770"
        owner: "root"
        group: "root"

    - name: Copy rclone.conf
      ansible.builtin.template:
        src: templates/rclone.conf.j2
        dest: "/etc/kolla/mariadb-s3-backup/rclone.conf"
        owner: "root"
        group: "root"
        mode: "660"

    - name: Copy public gpg key
      ansible.builtin.template:
        src: files/testbed-backup-public-key.asc
        dest: "/etc/kolla/mariadb-s3-backup/testbed-backup-public-key.asc"
        owner: "root"
        group: "root"
        mode: "660"

    - name: Import GPG public key from file
      ansible.builtin.command:
        cmd: gpg --import /etc/kolla/mariadb-s3-backup/testbed-backup-public-key.asc
      register: gpg_import_result
      changed_when: "'imported' in gpg_import_result.stderr"

- name: Setup mariadb backups on manager
  hosts: manager
  become: true
  gather_facts: false
  vars_files:
    - configuration.yml
    - secrets.yml
  vars:
    mariadb_s3_backup_rclone_docker_registry: "ghcr.io"
    mariadb_s3_backup_rclone_docker_image: "rclone/rclone"
    mariadb_s3_backup_rclone_docker_tag: "1.74.3"
    mariadb_s3_backup_rclone_image_full: "{{ mariadb_s3_backup_rclone_docker_registry }}/{{ mariadb_s3_backup_rclone_docker_image }}:{{ mariadb_s3_backup_rclone_docker_tag }}"

    mariadb_s3_backup_rclone_config_volume: "rclone-config"
    mariadb_s3_backup_rclone_s3_provider: "Ceph"
    mariadb_s3_backup_rclone_identifier: "backup"

    mariadb_s3_backup_s3_hostname: "api.bfe2.teutostack.de"
    mariadb_s3_backup_s3_port: "6780"
    mariadb_s3_backup_s3_endpoint: "https://{{ mariadb_s3_backup_s3_hostname}}:{{mariadb_s3_backup_s3_port}}"
    mariadb_s3_backup_s3_provider: "ceph"
    mariadb_s3_backup_s3_bucket: "mariadb-backups"
    mariadb_s3_backup_s3_virtual_hosted_style_bucket: false
    mariadb_s3_backup_s3_path: ""
    mariadb_s3_backup_s3_region: ""
    mariadb_s3_backup_s3_access_key_id: ""
    mariadb_s3_backup_s3_secret_access_key: ""
  tasks:
    - name: Deploy systemd timers
      ansible.builtin.template:
        src: "files/{{ item }}.timer"
        dest: /etc/systemd/system/{{ item }}.timer
        owner: root
        group: root
        mode: "0644"
      loop:
        - latest-full-mariadb-backup
        - latest-incremental-mariadb-backup
      notify: Reload systemd

    - name: Deploy systemd units
      ansible.builtin.template:
        src: "files/{{ item }}.service"
        dest: "/etc/systemd/system/{{ item }}.service"
        owner: root
        group: root
        mode: "0644"
      loop:
        - latest-full-mariadb-backup
        - latest-incremental-mariadb-backup
      notify: Reload systemd

    - name: Flush handlers to ensure daemon is reloaded
      ansible.builtin.meta: flush_handlers

    - name: Enable systemd services
      ansible.builtin.systemd_service:
        name: "{{ item }}.service"
        enabled: true
      loop:
        - latest-full-mariadb-backup
        - latest-incremental-mariadb-backup
      notify: Reload systemd

    - name: Enable systemd timers
      ansible.builtin.systemd_service:
        name: "{{ item }}.timer"
        enabled: true
        state: started
      loop:
        - latest-full-mariadb-backup
        - latest-incremental-mariadb-backup
      notify: Reload systemd

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
