---
- name: Post clean play
  hosts: all

  vars_files:
    - vars/cloud_envs.yml

  tasks:
    - name: Set cloud_env fact (Zuul deployment)
      ansible.builtin.set_fact:
        cloud_env: "{{ cloud_envs[hostvars[groups['all'][0]]['nodepool']['label']] }}"
      when: "'nodepool' in hostvars[groups['all'][0]]"

    - name: Set cloud_env fact (local deployment)
      ansible.builtin.set_fact:
        cloud_env: "{{ testbed_environment | default('ci') }}"
      when: "'nodepool' not in hostvars[groups['all'][0]]"

    - name: Make clean
      ansible.builtin.shell:
        chdir: "{{ ansible_user_dir }}/src/github.com/osism/testbed/terraform"
        cmd: make ENVIRONMENT={{ cloud_env }} clean 2>&1

- name: Post output play
  hosts: all

  vars:
    stage_dir: "{{ ansible_user_dir }}/zuul-output"

  roles:
    - stage-output
