---
- hosts: all

  vars:
    cloud_env: "{{ testbed_environment | default('ci') }}"

  tasks:
    - name: Make clean
      ansible.builtin.shell:
        chdir: "{{ ansible_user_dir }}/src/github.com/osism/testbed/terraform"
        cmd: make ENVIRONMENT={{ cloud_env }} clean 2>&1

- hosts: all

  vars:
    stage_dir: "{{ ansible_user_dir }}/zuul-output"

  roles:
    - stage-output
