---
- hosts: all
  tasks:
    - name: make clean
      ansible.builtin.shell:
        chdir: "{{ ansible_user_dir }}/src/github.com/osism/testbed/terraform"
        cmd: make clean 2>&1

- hosts: all
  roles:
    - stage-output
  vars:
    stage_dir: "{{ ansible_user_dir }}/zuul-output"
