---
- hosts: all
  vars:
    ansible_galaxy: ~/venv/bin/ansible-galaxy
    ansible_playbook: ~/venv/bin/ansible-playbook
    basepath: "{{ ansible_user_dir }}/src/github.com/osism/testbed"
    cloud_env: betacloud-ci
    manager_address_file: "{{ basepath }}/terraform/.MANAGER_ADDRESS.{{ cloud_env }}"
    manual_deploy: false
    repo_path: "{{ ansible_user_dir }}/src/github.com"
  tasks:
    - name: make CI deployment with terraform
      shell:
        chdir: "{{ basepath }}/terraform"
        cmd: make ENVIRONMENT={{ cloud_env }} deploy-openstack
      when: not manual_deploy
    - name: fetch manager_host address
      shell: cat "{{ manager_address_file }}"
      register: manager_address
    - name: set manager_host address
      set_fact:
        manager_host: "{{ manager_address.stdout.split('=')[1] }}"
    - name: update ansible collections
      shell:
        chdir: "{{ ansible_user_dir }}"
        cmd: |
          {{ ansible_galaxy }} collection install --force "{{ ansible_user_dir }}/src/github.com/osism/ansible-collection-commons"
          {{ ansible_galaxy }} collection install --force "{{ ansible_user_dir }}/src/github.com/osism/ansible-collection-services"
      when: not manual_deploy
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ manager_host }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 300
    - name: fetch manager ssh hostkey
      shell: "sleep 60; ssh-keyscan {{ manager_host }} >> {{ ansible_user_dir }}/.ssh/known_hosts"
    - name: run part 0
      shell:
        chdir: "{{ basepath }}/ansible"
        cmd: |
          cp ../terraform/.id* .
          {{ ansible_playbook }} -i ../terraform/inventory.{{ cloud_env }} --key-file .id_rsa.{{ cloud_env }} manager-part-0.yml -e cloud_env={{ cloud_env }} -e repo_path={{ repo_path }}
    - name: run part 1+2
      shell:
        chdir: "{{ basepath }}/ansible"
        cmd: |
          {{ ansible_playbook }} -i ../terraform/inventory.{{ cloud_env }} --key-file .id_rsa.{{ cloud_env }} manager-part-1.yml -e cloud_env={{ cloud_env }} -e repo_path={{ repo_path }}
    - name: run part 3
      shell:
        chdir: "{{ basepath }}/ansible"
        cmd: "ssh -i .id_rsa.{{ cloud_env }} dragon@{{ manager_host }} /opt/configuration/ansible/manager.sh"
      when: not manual_deploy
    - name: run deployment checks
      shell:
        chdir: "{{ basepath }}/terraform"
        cmd: make ENVIRONMENT={{ cloud_env }} check
      when: not manual_deploy
