# Required to fulfill test tempest.api.identity.v3.test_users.IdentityV3UsersTest
[security_compliance]
lockout_failure_attempts = 2
lockout_duration = 5
password_expires_days = 90
unique_last_password_count = 3
