---
name: Build diskimage

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-diskimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - run: pip3 install -r diskimage/requirements.txt
      - run: bash scripts/001-install.sh
        working-directory: diskimage
      - run: bash scripts/002-build.sh
        working-directory: diskimage
