---
name: Check terraform syntax

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform-syntax.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform.yml'

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - 0.14.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Terraform validate
        run: make validate
        working-directory: ./terraform
        with:
          ENVIRONMENT: default
      - name: Terraform format
        run: terraform fmt -check
        working-directory: ./terraform
