---
name: Check terraform syntax

"on":
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform-syntax.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform.yml'

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - 1.2.7

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Terraform validate
        run: make validate
        working-directory: ./terraform
        env:
          ENVIRONMENT: default
      - name: Terraform format
        run: terraform fmt -check
        working-directory: ./terraform
