---
name: Check ansible inventory

"on":
  push:
    paths:
      - 'inventory/hosts'
      - '.github/workflows/check-ansible-inventory.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'inventory/hosts'
      - '.github/workflows/check-ansible-inventory.yml'

jobs:
  check-ansible-inventory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install ansible
      - run: ansible-inventory -i inventory/hosts --list
