---
name: Check ansible syntax

"on":
  push:
    paths:
      - 'environments/**.yml'
      - 'playbooks/**.yml'
      - '.github/workflows/check-ansible-syntax.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'environments/**.yml'
      - 'playbooks/**.yml'
      - '.github/workflows/check-ansible-syntax.yml'

jobs:
  check-ansible-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: osism/ansible-lint-action@v1.0.0
