---
name: Check yaml syntax

"on":
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/check-yaml-syntax.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/check-yaml-syntax.yml'

jobs:
  check-yaml-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip3 install yamllint
      - run: yamllint .
