---
name: Daily citycloud

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '.github/workflows/daily-citycloud.yml'
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

jobs:
  daily-citycloud-cleanup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        openstack-version:
          - victoria

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
      - name: Prepare use of openstack
        shell: bash
        working-directory: ./terraform
        env:
          OPENSTACK: ${{ secrets.OPENSTACK }}
        run: |
          echo "$OPENSTACK" > clouds.yaml
      - name: Prepare use of minio
        shell: bash
        working-directory: ./terraform
        env:
          MINIO: ${{ secrets.MINIO }}
        run: |
          echo "$MINIO" > minio.env
          cp minio.tf.disabled minio.tf
      - name: Initialization
        run: make init
        working-directory: ./terraform
      - name: Remove existing environment
        run: make ENVIRONMENT=citycloud clean || exit 0
        working-directory: ./terraform

  daily-citycloud-deploy:
    needs: daily-citycloud-cleanup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        openstack-version:
          - victoria

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
      - name: Prepare use of openstack
        shell: bash
        working-directory: ./terraform
        env:
          OPENSTACK: ${{ secrets.OPENSTACK }}
        run: |
          echo "$OPENSTACK" > clouds.yaml
      - name: Prepare use of minio
        shell: bash
        working-directory: ./terraform
        env:
          MINIO: ${{ secrets.MINIO }}
        run: |
          echo "$MINIO" > minio.env
          cp minio.tf.disabled minio.tf
      - name: Initialization
        run: make ENVIRONMENT=citycloud init
        working-directory: ./terraform
      - name: Deploy environment
        run: make ENVIRONMENT=citycloud deploy-openstack PARAMS="-var openstack_version=${{ matrix.openstack-version }} -var run_refstack=true -var run_rally=true"
        working-directory: ./terraform
