---
name: PR labeler

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/pr-labeler-action@v4
