---
name: Check ansible syntax

on:
  push:
    paths:
      - 'environments/**.yml'
      - 'playbooks/**.yml'
  pull_request:
    paths:
      - 'environments/**.yml'
      - 'playbooks/**.yml'

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
