---
name: Update manager images

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-manager-images:
    if: github.repository == 'osism/testbed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            pip3 install jinja2
            pip3 install requests
            pip3 install pyyaml
            curl -o images.yml https://raw.githubusercontent.com/osism/cfg-generics/main/environments/manager/images.yml
            curl -o render-images.py https://raw.githubusercontent.com/osism/cfg-generics/main/src/render-images.py
            python3 render-images.py
            rm -f render-images.py
            mv images.yml environments/manager/images.yml
          COMMIT_EMAIL: 'bot@osism.tech'
          COMMIT_MESSAGE: |
            chore: update versions in environments/manager/images.yml

            Signed-off-by: OSISM Bot <bot@osism.tech>
          COMMIT_NAME: 'OSISM Bot'
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: 'update-manager-images'
          PR_BRANCH_PREFIX: 'chore/'
          PR_TITLE: 'chore: update versions in environments/manager/images.yml'
